blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/opentreecz/.github/blob/master/SUPPORT.md
    about: Find out where to get help and support.

  - name: Documentation
    url: https://opentreecz.github.io/
    about: Read the full project documentation on our website.

  - name: Security Vulnerability
    url: https://github.com/opentreecz/.github/blob/master/SECURITY.md
    about: Report a security vulnerability (do NOT use public issues for this).
